/**
 * Device Filter class, used on BOMSearchDevice.vfp
 * @author: Jimens Lima - jimens@motorola.com
 */
public class BOMDeviceFilter {

    public String internalName {get;set;}
    public String launchType   {get;set;}
    public String software     {get;set;}
    public String swKit        {get;set;}
    public String salesModel   {get;set;}
    public String deviceId     {get;set;}
    public String carrierName  {get;set;}
    public String countryCode  {get;set;}
    public String saStatus     {get;set;}
}