/**********************************************************/
// Created by: José Elias Araújo
// Created Date: 03/14/2014
// Last Modified: José Elias Araújo
// Last Modified by: 03/19/2014
//
// Description:
// This class represents exception used by exception 
// handling implemented in all classes.
// 
// Test Class: 
// 
/**********************************************************/
public class EmporiumException extends Exception{
    

}