/**********************************************************/
// Created by: José Elias Araújo
// Created Date: 03/14/2014
// Last Modified: José Elias Araújo
// Last Modified by: 03/19/2014
//
// Description:
// This class is used by an exception handling when any problem
// occurs during data importing.
// 
// Test Class: 
// 
/**********************************************************/
public class LaunchCalException extends Exception{

}